### ISSUE TITLE
file fields are not imported with node export/data import export modules

### ISSUE THREAD

**Issue by szmediathek** [szmediathek/szmediathek#3]

**Comment by johnsmithm** [comment]
if the files are already in the /default/files/ directory, the modules gives fatal error

**Comment by johnsmithm** [comment]
field files are imported with node export, but the files are dublicated

**Comment by johnsmithm** [comment]
todo:
- see what are the differences between the file that are imported and the file that are made
- chnage the file that are imported so that it will be not needed to make another one

**Comment by johnsmithm** [comment]
deleted file's fid in order to make new file.
however if there is already a file with that uri the script shows an error(but it is not posible that some items to have same uri, just is one have migrated same node two times)
