### ISSUE TITLE
import group fields to mediendatai

### ISSUE THREAD

**Issue by szmediathek** [szmediathek/szmediathek#4]

**Comment by johnsmithm** [comment]
import group fields

**Comment by johnsmithm** [comment]
also import ds templates

**Comment by johnsmithm** [comment]
bundle copy says that it suports fields group

**Comment by johnsmithm** [comment]
tried to import field group of mediadatai content type using bulk-export module.
there is no changes in the new mediathek site.

**Comment by johnsmithm** [comment]
tried to import group field with features module, without any success

**Comment by johnsmithm** [comment]
some group field appears in the full view, but they are not in the right place, and the children are not in the right field group!

**Comment by johnsmithm** [comment]
field group are imported with features or/and bundle copy, but the weigth and activation/disactivation are not correct

**Comment by johnsmithm** [comment]
the idea is to use a test content type with group field and try to import it with different features for migration.

**Comment by johnsmithm** [comment]
i have made a test conent type, i have imported first the field, then the group field, and with features i have imported ds setting(i have not tested the field collection).
Next step is to delete the mediendatei content type and import it using the way described above!

**Comment by johnsmithm** [comment]
errors while importing mediendatei with bundle copy because of the field collection. 
next way of working:
- copy just content type without fields with bundle copy
- copy field collection with features
- copy normal field with bundle copy
- copy group field with bundle copy
- copy ds setting with features

**Comment by johnsmithm** [comment]
the following way of importing fields group worked:
- imported mediendatei with fieldcollection with bundle copy
- imported others field with small groups with bundle coppy
- imported field group related to form with bundle coppy
- imported field collection fields with features
