### ISSUE TITLE
Show creator of support ticket

### ISSUE THREAD

**Issue by cnhagen** [szmediathek/szmediathek#42]
When support tickets are created by one user, his or her name should be shown to those who view this ticket. 
_(Sometimes not all assignments are obvius, so you know how to ask for further details.)_

**Comment by johnsmithm** [comment]
i have added a new field in the display for the support ticket content type with a link to the profile of the person who made the support ticket with the label: 'Author'.
![adding author to the support ticket](https://cloud.githubusercontent.com/assets/10476109/26026456/d8e2a41a-37fb-11e7-8f72-3a57e4ae5552.png)
