### ISSUE TITLE
Make user list searchable

### ISSUE THREAD

**Issue by cnhagen** [szmediathek/szmediathek#55]
It occasionally occurs that I am looking for one specific user (e.g. when someone with a student-role starts working for us and his/her role must be changed to "hiwi"). Now I have to scroll through a never-ending list of user names and look for that person which sometimes takes very long...
(Maybe it is already possible somehow and I just don't know how?)

**Comment by johnsmithm** [comment]
there is a page reachable from administration menu(Verwaltung), search for a user. the users role can be change using a operation from selectbox. other solution could be making the list of users from that page(/benutzersuche) links to the user's profile.

**Comment by cnhagen** [comment]
Oh! I am sorry...
I was always using the wrong path. I went to ADMIN (Startseite>Verwaltung) and then to "Benutzer". There, you get a list of all users that is not searchable. 
Thank you!
