### ISSUE TITLE
mount the sites/default/files to host

### ISSUE THREAD

**Issue by szmediathek** [szmediathek/szmediathek#7]

**Comment by johnsmithm** [comment]
use symbolik links, it is not seen by the drupal

**Comment by johnsmithm** [comment]
think we can use a symbolik link to use files directory from host

**Comment by johnsmithm** [comment]
i have asked drupal comunity:
https://www.drupal.org/node/2736447#comment-11555557
I will try to use Virtual File System!

**Comment by johnsmithm** [comment]
dd if=/dev/zero of=./filesyst bs=10485760 count=1
sudo losetup /dev/loop0 ./filesyst
sudo mkfs.ext3 /dev/loop0
sudo mount /dev/loop0 /tmp/firstfile
sudo mount /dev/loop0 /tmp/secondfile

this is the way VFS works

**Comment by johnsmithm** [comment]
done

**Comment by johnsmithm** [comment]
added VFS in the localmediathek server, It works
