### ISSUE TITLE
configure solr 

### ISSUE THREAD

**Issue by szmediathek** [szmediathek/szmediathek#8]
- add indexes
- add facet blocks

**Comment by johnsmithm** [comment]
find a way to import the indexes and configuration(maybe features module)
also the dev/stage/life sites have different solr server - it is needed a solution for that

**Comment by johnsmithm** [comment]
when trying to index the content error apears and the content is not indexed.

**Comment by johnsmithm** [comment]
reimport the index and filters, or make a new index and make a test view search page in order to test the solr server. still i have not seen any search actions.

**Comment by johnsmithm** [comment]
added a test index for mediedatei.

**Comment by johnsmithm** [comment]
create a test solr server, and add the index for that server, for mediendatei and for other types in order to identify the error source

**Comment by johnsmithm** [comment]
the problem is in the solr instance of the server from drupal. I have created new server, and added the indexes from another server and the index started indexing.
